export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const ADD_CONTACTS = 'ADD_CONTACTS';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const SHOW_CONTACT = 'SHOW_CONTACT';
